config/routes.rb
Rails.application.routes.draw do

  get '/users/', to: "users#index", as: 'users'
  get '/users/:id', to: "users#show", as: 'user'

  get '/users/:id/favorites/new', to: "favorites#new", as: 'new_user_favorite'
  post '/users/:id/favorites', to: "favorites#create"

  get '/users/:id/palettes/new', to: "palettes#new", as: 'new_user_palette'
  post '/users/:id/palettes', to: "palettes#create"

  get '/colors', to: "colors#index", as: 'colors'
  get '/colors/:id', to: "colors#show", as: 'color'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :color
  belongs_to :user
end

app/models/palette.rb
class Palette < ApplicationRecord
  belongs_to :user
  
  has_many :palette_colors
  has_many :colors, through: :palette_colors

  validates :name, presence: true
end

app/models/palette_color.rb
class PaletteColor < ApplicationRecord
  belongs_to :palette
  belongs_to :color
end

app/models/user.rb
class User < ApplicationRecord
    has_many :palettes

    has_many :favorites
    has_many :colors, through: :favorites

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/colors_controller.rb
class ColorsController < ApplicationController

    def index

        @colors = Color.all
    
    end

    def show

        @color = Color.find(params[:id])
    
    end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

    def new

        @user = User.find(params[:id])
    
    end

    def create

        @user = User.find(params[:id])


        if params["hex_code"].length != 7 || params["hex_code"][0] != '#'

            flash[:errors] = ["A hex code must have the format '#xxxxxx'"]
            redirect_to new_user_favorite_path(@user)


        elsif params["hex_code"].split("")[1, 6].find{|char| !(char =~ /[a-f0-9]/)}
            flash[:errors] = ["Characters must be numerals or lower case letters between a and f."]
            redirect_to new_user_favorite_path(@user)
            
        else
            @color = Color.find_or_create_by(hex_code: params["hex_code"])

            favorite = Favorite.find_by(color_id: @color.id, user_id: @user.id)

            if !favorite
                Favorite.create(color_id: @color.id, user_id: @user.id)
            end

            redirect_to user_path(@user)
        end

    end
    
end

app/controllers/palettes_controller.rb
class PalettesController < ApplicationController
    
    def new

        @user = User.find(params[:id])
    
    end

    def create

        @user = User.find(params[:id])

        if !params[:color_ids]
            flash[:errors] = ["A palette must have at least one color."]
        else
            @palette = Palette.new(name: params[:name], user_id: @user.id)

            if @palette.valid?
                @palette.save
                params[:color_ids].each do |id|
                    PaletteColor.create(palette_id: @palette.id , color_id: id)
                end
            else
                flash[:errors] = @palette.errors.full_messages
            end
        end

        if flash[:errors]
            redirect_to new_user_palette_path(@user)
        else
            redirect_to user_path(@user)
        end
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index

    @users = User.all

  end

  def show

    @user = User.find(params[:id])
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/colors/index.html.erb
<div id="colors-container">
    <% @colors.each do |color| %>

        <div class="color-swatch-container">
            <%= link_to color_path(color) do %>
                <div class="color-swatch" style="background:<%=color.hex_code%>;" ></div>
                <h4><%=color.name%></h4>
                <p><%=color.hex_code%></p>
            <% end %>
        </div>

    <% end %>
</div>

app/views/colors/show.html.erb
<div id="color-show-container" style="background: <%= @color.hex_code %>">

<h1 class="color-name"><%= @color.name %></h1>
<h3 class="color-hex"><%= @color.hex_code %></h3>

<h2 class="color-heading">Users who love this color:</h2>

<div id="favoriting-users">
    <% @color.users.each do |user| %>
        <div class="user-index-card">
            <%= link_to user_path(user) do %>
                <h2><%= user.name %></h2>
                <h3><%= user.position %></h3>
                <div class="image-frame" style="background:<%= @color.hex_code %>" >
                    <img src=<%= user.image_url %>>
                </div>
                <p><%= user.colors.count %> favorite colors</p>
                <p><%= user.palettes.count %> saved palettes</p>
            <% end %>
        </div>
    <% end %>
</div>



<div>